### ISSUE TITLE
AttributeError: 'list' object has no attribute 'items'

### ISSUE THREAD

**Issue by faizanahmadfg** [arunponnusamy/gender-detection-keras#24]
i have run this repository multiple times but now from last week i'm facing this error

**Comment by samsungderdull** [comment]
Same here.

python detect_gender.py -i sample_input.jpg

`Traceback (most recent call last):
  File "detect_gender.py", line 33, in <module>
    model = load_model(model_path)
  File "/home/xxx/anaconda3/envs/GenderDetection/lib/python3.7/site-packages/tensorflow/python/keras/saving/save.py", line 184, in load_model
    return hdf5_format.load_model_from_hdf5(filepath, custom_objects, compile)
  File "/home/xxx/anaconda3/envs/GenderDetection/lib/python3.7/site-packages/tensorflow/python/keras/saving/hdf5_format.py", line 178, in load_model_from_hdf5
    custom_objects=custom_objects)
  File "/home/xxx/anaconda3/envs/GenderDetection/lib/python3.7/site-packages/tensorflow/python/keras/saving/model_config.py", line 55, in model_from_config
    return deserialize(config, custom_objects=custom_objects)
  File "/home/xxx/anaconda3/envs/GenderDetection/lib/python3.7/site-packages/tensorflow/python/keras/layers/serialization.py", line 109, in deserialize
    printable_module_name='layer')
  File "/home/xxx/anaconda3/envs/GenderDetection/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 362, in deserialize_keras_object
    config, module_objects, custom_objects, printable_module_name)
  File "/home/xxx/anaconda3/envs/GenderDetection/lib/python3.7/site-packages/tensorflow/python/keras/utils/generic_utils.py", line 325, in class_and_config_for_serialized_keras_object
    for key, item in cls_config.items():
AttributeError: 'list' object has no attribute 'items'`
